cyclomatic_complexity: 12
file_length: 550
function_body_length: 80
function_parameter_count: 5
line_length: 400
type_body_length: 300
identifier_name:
  min_length:
    error: 1
    warning: 1
  excluded:
    - N

disabled_rules:
 - trailing_whitespace
 - todo
 - unused_optional_binding

excluded:
 - Carthage